image: node:10.19.0

pipelines:
  default:
    - step:
        caches:
          - node
          - yarncustom
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn
          - yarn lint
          - yarn build
definitions:
  caches:
    yarncustom: /usr/local/share/.cache/yarn/v1