 
name: Build Docker image
on:
  push:
    tags:
      - v*
  pull_request:
    branches:    
      - master 
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.1.0
    
    - uses: actions/setup-node@v1.4.1
      with:
        node-version: '10.19.0'
    - id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: install dependencies
      run: yarn

    - name: analyse code
      run: yarn lint

    - name: build
      run: yarn build

    - name: Build and push Docker image
      env:
        IMAGE_NAME: ${{ secrets.CONTAINER_REGISTRY }}/krossboard-ui
        REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      run: |
        export IMAGE_VERSION=$BITBUCKET_COMMIT
        docker build -t $IMAGE_NAME:$IMAGE_VERSION .
        docker tag $IMAGE_NAME:$IMAGE_VERSION $IMAGE_NAME:latest
        docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
        docker push $IMAGE_NAME